### ISSUE TITLE
Replace title react app text with URL Shortner-DSC TIET

### ISSUE THREAD

**Issue by OtoZacpal** [developer-student-club-thapar/urlShortner#85]
Tab Title has to be replaced with 'URL Shortner-DSC TIET' ,instead of 'React App'

**Comment by shivambhatia5432** [comment]
Hi, I tried solving this issue do check pr #88 for this issue

**Comment by Harshi7016** [comment]
Is the issue resolved?

**Comment by shivambhatia5432** [comment]
I corrected this issue on #89 please check

**Comment by Harshi7016** [comment]
<title>Thapar University URL Shortne</title>
Hey, I guess you missed an `r` in your PR

**Comment by shivambhatia5432** [comment]
I corrected this issue on #89 please check
